import {
  Home,
  Users,
  ShoppingCart,
  Package,
  FolderTree,
  ShoppingBag,
  Truck,
  MapPin,
  Route,
  MessageSquare,
  User2,
  Store,
  ClipboardList,
  Warehouse,
  Headphones,
  Wallet,
  PackageCheck,
  CreditCard,
  BarChart3,
  Droplets,
  ArrowRightLeft,
  Settings2,
  CalendarCheck,
  FileText,
  Building2,
  LayoutDashboard,
  Factory,
  PackageX,
  Receipt,
  UserCog,
  Banknote,
  FileMinus2,
  FilePlus2,
  FileSpreadsheet,
  Phone,
  IndianRupee,
  UserX,
  BookOpen,
  Scale,
  Landmark,
  RefreshCw,
  AlertTriangle,
  Lock,
  ClipboardCheck,
  Megaphone,
  FlaskConical,
  BadgeCheck,
  Star,
  type LucideIcon,
} from "lucide-react"

import type { UserRole } from "@/lib/types/database"

export type MenuItem = {
  title: string
  url: string
  icon: LucideIcon
  roles: UserRole[]
}

export type MenuGroup = {
  label: string
  items: MenuItem[]
}

export const menuGroups: MenuGroup[] = [
  {
    label: "Overview",
    items: [
      { title: "Dashboard", url: "/dashboard", icon: Home, roles: ["admin", "warehouse", "vendors", "delivery_driver"] },
      { title: "Dashboard V2", url: "/dashboard/dashboard-v2", icon: LayoutDashboard, roles: ["admin"] },
      { title: "Factory Dashboard", url: "/dashboard/factory-dashboard", icon: Factory, roles: ["admin", "factories"] },
      { title: "Announcements", url: "/dashboard/announcements", icon: Megaphone, roles: ["admin"] },
      { title: "Blogs", url: "/dashboard/blogs", icon: BookOpen, roles: ["admin"] },
      { title: "Lab Tests", url: "/dashboard/lab-tests", icon: FlaskConical, roles: ["admin"] },
      { title: "Licenses", url: "/dashboard/licenses", icon: BadgeCheck, roles: ["admin"] },
      { title: "Reviews", url: "/dashboard/reviews", icon: Star, roles: ["admin"] },
      { title: "Distributor Panel", url: "/dashboard/distributor-panel", icon: Building2, roles: ["main_distributor", "sub_distributor"] },
      { title: "Retailer Panel", url: "/dashboard/retailer-panel", icon: Store, roles: ["retailer"] },
      { title: "Vendor Panel", url: "/dashboard/vendor-panel", icon: Factory, roles: ["vendors"] },
      { title: "Agent Dashboard", url: "/dashboard/agent-dashboard", icon: Headphones, roles: ["admin", "customer_support"] },
    ],
  },
  {
    label: "Support",
    items: [
      { title: "Customer Support", url: "/dashboard/support", icon: Headphones, roles: ["admin", "customer_support"] },
      { title: "MyOperator", url: "/dashboard/myoperator", icon: Phone, roles: ["admin", "customer_support"] },
      { title: "Support Tickets", url: "/dashboard/tickets", icon: MessageSquare, roles: ["admin", "customer_support"] },
    ],
  },
  {
    label: "Customer Engagement",
    items: [
      { title: "Payment Collection", url: "/dashboard/payment-collection", icon: IndianRupee, roles: ["admin", "customer_support", "main_distributor"] },
      { title: "Inactive Customers", url: "/dashboard/inactive-customers", icon: UserX, roles: ["admin", "customer_support", "main_distributor"] },
    ],
  },
  {
    label: "Sales & Orders",
    items: [
      { title: "Actual Physical Stock", url: "/dashboard/orders/actual-stock", icon: Package, roles: ["admin", "factories"] },
      { title: "Orders V2", url: "/dashboard/orders-v2", icon: LayoutDashboard, roles: ["admin", "warehouse", "customer_support", "factories", "main_distributor", "sub_distributor"] },
      { title: "Point of Sale", url: "/dashboard/pos", icon: CreditCard, roles: ["admin", "retailer"] },
      { title: "Order from Factory", url: "/dashboard/order-from-factory/new", icon: Factory, roles: ["admin", "factories"] },
      { title: "Warehouse Orders", url: "/dashboard/warehouse-orders", icon: Warehouse, roles: ["admin", "main_distributor", "sub_distributor"] },
      { title: "Partner Orders", url: "/dashboard/partner-orders", icon: ClipboardList, roles: ["admin", "main_distributor"] },
      { title: "Agent Commissions", url: "/dashboard/agent-commissions", icon: Wallet, roles: ["admin"] },
      { title: "Easebuzz Transactions", url: "/dashboard/easebuzz-transactions", icon: Banknote, roles: ["admin", "main_distributor", "sub_distributor"] },
    ],
  },
  {
    label: "People",
    items: [
      { title: "My Customers", url: "/dashboard/my-customers", icon: Users, roles: ["main_distributor", "sub_distributor", "retailer"] },
      { title: "Customers", url: "/dashboard/customers", icon: Users, roles: ["admin", "warehouse", "customer_support"] },
      { title: "Customers V2", url: "/dashboard/customers/v2", icon: Users, roles: ["admin", "customer_support", "factories"] },
      { title: "Users", url: "/dashboard/users", icon: User2, roles: ["admin"] },
      { title: "Attendance", url: "/dashboard/attendance", icon: CalendarCheck, roles: ["admin"] },
      { title: "Distributors", url: "/dashboard/distributors", icon: Building2, roles: ["admin", "warehouse", "factories"] },
      { title: "Retailers", url: "/dashboard/retailers", icon: Store, roles: ["admin", "warehouse"] },
      { title: "Retailer Payments", url: "/dashboard/special-retailers", icon: IndianRupee, roles: ["admin", "warehouse", "retailer"] },
      { title: "Vendors", url: "/dashboard/vendors", icon: ShoppingBag, roles: ["admin", "warehouse", "main_distributor", "sub_distributor", "factories"] },
      { title: "Delivery Partners", url: "/dashboard/delivery-partners", icon: Truck, roles: ["admin"] },
    ],
  },
  {
    label: "Logistics",
    items: [
      { title: "Route Assignments", url: "/dashboard/route-assignments", icon: Route, roles: ["admin", "main_distributor"] },
      { title: "Delivery Sheets", url: "/dashboard/delivery-sheets", icon: ClipboardList, roles: ["admin", "main_distributor"] },
      { title: "E-Way Bill", url: "/dashboard/ewaybill", icon: FileText, roles: ["admin", "warehouse", "factories"] },
      { title: "Courier Partners", url: "/dashboard/courier-partners", icon: Truck, roles: ["admin"] },
      { title: "Shiprocket Orders", url: "/dashboard/shiprocket", icon: PackageX, roles: ["admin", "customer_support"] },
      { title: "Routes", url: "/dashboard/routes", icon: MapPin, roles: ["admin", "main_distributor"] },
      { title: "My Deliveries", url: "/dashboard/delivery-drivers", icon: PackageCheck, roles: ["delivery_driver"] },
      { title: "Delivery Reviewer", url: "/dashboard/delivery-reviewer", icon: Wallet, roles: ["admin", "main_distributor", "sub_distributor"] },
    ],
  },
  {
    label: "Inventory Management",
    items: [
      { title: "Manufacturing Opening Stock", url: "/dashboard/manufacturing-opening-stock", icon: Factory, roles: ["admin", "factories"] },
      { title: "My Stock", url: "/dashboard/my-stock", icon: Package, roles: ["main_distributor", "sub_distributor", "retailer"] },
      { title: "Warehouse Stock", url: "/dashboard/warehouse-stock", icon: BarChart3, roles: ["admin", "warehouse", "factories"] },
      { title: "Warehouse Opening Stock", url: "/dashboard/warehouse-opening-stock", icon: Warehouse, roles: ["admin", "warehouse", "factories"] },
      { title: "Stock Inventory", url: "/dashboard/stock", icon: Package, roles: ["admin", "warehouse", "factories"] },
      { title: "Loose Stock", url: "/dashboard/loose-stock", icon: Droplets, roles: ["admin", "warehouse", "factories"] },
      { title: "Loose Opening Stock", url: "/dashboard/loose-opening-stock", icon: Droplets, roles: ["admin", "warehouse", "factories"] },
      { title: "Warehouses (Godowns)", url: "/dashboard/godowns", icon: Warehouse, roles: ["admin", "warehouse", "factories"] },
      { title: "Stock Transfers", url: "/dashboard/stock-transfers", icon: ArrowRightLeft, roles: ["admin", "warehouse", "factories", "retailer"] },
      { title: "Distributor Stock", url: "/dashboard/distributor-stock", icon: Building2, roles: ["admin", "warehouse"] },
      { title: "Distributor Opening Stock", url: "/dashboard/distributor-opening-stock", icon: Building2, roles: ["admin", "warehouse"] },
      { title: "Retailer Stock", url: "/dashboard/retailer-stock", icon: Store, roles: ["admin", "warehouse"] },
      { title: "Retailer Opening Stock", url: "/dashboard/retailer-opening-stock", icon: Store, roles: ["admin", "warehouse"] },
      { title: "Material Mapping", url: "/dashboard/stock/material-mapping", icon: Settings2, roles: ["admin", "warehouse", "factories"] },
      { title: "Stock Ledger", url: "/dashboard/stock-ledger", icon: ClipboardList, roles: ["admin", "warehouse", "factories"] },
      { title: "Inventory Valuation", url: "/dashboard/inventory-valuation", icon: BarChart3, roles: ["admin", "warehouse"] },
      { title: "Stock Write-offs", url: "/dashboard/stock-write-offs", icon: AlertTriangle, roles: ["admin", "warehouse"] },
      { title: "Reorder Management", url: "/dashboard/reorder-management", icon: RefreshCw, roles: ["admin", "warehouse"] },
    ],
  },
  {
    label: "Products & Catalog",
    items: [
      { title: "Products", url: "/dashboard/products", icon: Package, roles: ["admin", "factories", "main_distributor", "retailer", "sub_distributor", "customer_support"] },
      { title: "Bulk Editor", url: "/dashboard/products-bulk-edit", icon: Package, roles: ["admin", "factories"] },
      { title: "Categories", url: "/dashboard/categories", icon: FolderTree, roles: ["admin", "factories"] },
    ],
  },
  {
    label: "Procurement",
    items: [
      { title: "Purchases", url: "/dashboard/purchases", icon: ShoppingBag, roles: ["admin", "factories", "main_distributor", "sub_distributor"] },
      { title: "Goods Receipt Notes", url: "/dashboard/goods-receipt-notes", icon: ClipboardCheck, roles: ["admin", "warehouse", "factories"] },
      { title: "Credit Notes", url: "/dashboard/credit-notes", icon: FileMinus2, roles: ["admin", "factories"] },
      { title: "Debit Notes", url: "/dashboard/debit-notes", icon: FilePlus2, roles: ["admin", "factories"] },
      { title: "Expenses", url: "/dashboard/expenses", icon: Wallet, roles: ["admin", "factories", "main_distributor", "sub_distributor"] },
      { title: "My Expenses", url: "/dashboard/my-expenses", icon: Wallet, roles: ["retailer"] },
    ],
  },
  {
    label: "Accounting",
    items: [
      { title: "Chart of Accounts", url: "/dashboard/accounting/chart-of-accounts", icon: BookOpen, roles: ["admin"] },
      { title: "Journal Entries", url: "/dashboard/accounting/journal-entries", icon: FileText, roles: ["admin"] },
      { title: "Trial Balance", url: "/dashboard/accounting/trial-balance", icon: Scale, roles: ["admin"] },
      { title: "Account Ledger", url: "/dashboard/accounting/ledger", icon: BookOpen, roles: ["admin"] },
      { title: "Tax Ledger (GST)", url: "/dashboard/accounting/tax-ledger", icon: Receipt, roles: ["admin"] },
      { title: "AP Aging", url: "/dashboard/accounting/ap-aging", icon: CreditCard, roles: ["admin"] },
      { title: "AR Aging", url: "/dashboard/accounting/ar-aging", icon: Users, roles: ["admin"] },
      { title: "Reconciliation", url: "/dashboard/accounting/reconciliation", icon: Landmark, roles: ["admin", "warehouse", "customer_support", "factories", "main_distributor", "sub_distributor", "retailer", "vendors", "delivery_driver"] },
      { title: "Period Close", url: "/dashboard/accounting/period-close", icon: Lock, roles: ["admin"] },
    ],
  },
  {
    label: "Reports",
    items: [
      { title: "Orders Report", url: "/dashboard/reports/orders", icon: ShoppingCart, roles: ["admin", "customer_support"] },
      { title: "Purchase Report", url: "/dashboard/reports/purchases", icon: ShoppingBag, roles: ["admin", "factories"] },
      { title: "Customers Report", url: "/dashboard/reports/customers", icon: Users, roles: ["admin", "customer_support"] },
      { title: "User Transactions", url: "/dashboard/reports/user-transactions", icon: UserCog, roles: ["admin"] },
      { title: "GST Orders Report", url: "/dashboard/reports/gst-orders", icon: Receipt, roles: ["admin"] },
      { title: "GST Payable", url: "/dashboard/reports/gst-payable", icon: Landmark, roles: ["admin", "factories", "main_distributor", "sub_distributor", "retailer"] },
      { title: "Balance Sheet", url: "/dashboard/reports/balance-sheet", icon: FileText, roles: ["admin"] },
      { title: "Profit & Loss", url: "/dashboard/reports/profit-and-loss", icon: BarChart3, roles: ["admin"] },
      { title: "Tally Export", url: "/dashboard/reports/tally-export", icon: FileSpreadsheet, roles: ["admin"] },
      { title: "GSTR-1", url: "/dashboard/reports/gstr-1", icon: FileText, roles: ["admin"] },
      { title: "GSTR-3B", url: "/dashboard/reports/gstr-3b", icon: FileText, roles: ["admin"] },
      { title: "GSTR-2B Recon", url: "/dashboard/reports/gstr-2b-reconciliation", icon: FileText, roles: ["admin"] },
    ],
  },
]
